# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'CatCloud' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 5.0.1'
pod 'Alamofire'
pod 'AlamofireImage', '~> 4.1'
pod 'SwiftLint', '~> 0.54'
pod 'Toast-Swift', '~> 5.0.1'

  # Pods for CatCloud

end
